/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GatewayFactoryABIInterface extends Interface {
  getFunction(nameOrSignature: "deployGateway"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GatewayDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "deployGateway",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployGateway",
    data: BytesLike
  ): Result;
}

export namespace GatewayDeployedEvent {
  export type InputTuple = [
    gatewayAddr: AddressLike,
    gatewayOwnerAddr: AddressLike
  ];
  export type OutputTuple = [gatewayAddr: string, gatewayOwnerAddr: string];
  export interface OutputObject {
    gatewayAddr: string;
    gatewayOwnerAddr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GatewayFactoryABI extends BaseContract {
  connect(runner?: ContractRunner | null): GatewayFactoryABI;
  waitForDeployment(): Promise<this>;

  interface: GatewayFactoryABIInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployGateway: TypedContractMethod<
    [_gatewayOwner: AddressLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployGateway"
  ): TypedContractMethod<[_gatewayOwner: AddressLike], [string], "nonpayable">;

  getEvent(
    key: "GatewayDeployed"
  ): TypedContractEvent<
    GatewayDeployedEvent.InputTuple,
    GatewayDeployedEvent.OutputTuple,
    GatewayDeployedEvent.OutputObject
  >;

  filters: {
    "GatewayDeployed(address,address)": TypedContractEvent<
      GatewayDeployedEvent.InputTuple,
      GatewayDeployedEvent.OutputTuple,
      GatewayDeployedEvent.OutputObject
    >;
    GatewayDeployed: TypedContractEvent<
      GatewayDeployedEvent.InputTuple,
      GatewayDeployedEvent.OutputTuple,
      GatewayDeployedEvent.OutputObject
    >;
  };
}
