/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GatewayFactoryABI } from "./GatewayFactoryABI";
export * as factories from "./factories";
export { GatewayFactoryABI__factory } from "./factories/GatewayFactoryABI__factory";
